### ISSUE TITLE
General: Define REST Endpoints to Build Transactions

### ISSUE THREAD

**Issue by migueldingli1997** [ixofoundation/ixo-blockchain#123]
Currently, REST endpoints expect a user's private key, which they use similar to the CLI to sign and broadcast a message. As per standard Cosmos SDK practice, we need endpoints that instead accept everything except for the private key and return a properly formatted transaction which the external entity (component/user) can then sign and broadcast to the blockchain.

**Comment by Persistencesujith** [comment]
could you please divert to me the cosmos SDKs file which implemented the right way

**Comment by migueldingli1997** [comment]
Sure. In the ixo blockchain itself, the `bonds` module has the proper way of doing this implemented in its `client/rest/` folder:
https://github.com/ixofoundation/ixo-blockchain/tree/master/x/bonds/client/rest

**Comment by migueldingli1997** [comment]
Feel free to check out this folder for any other Cosmos SDK module, such as the `bank` module:
https://github.com/cosmos/cosmos-sdk/tree/master/x/bank/client/rest

**Comment by migueldingli1997** [comment]
Closed by #179
