### ISSUE TITLE
how to stake with custom coin denomination

### ISSUE THREAD

**Issue by jjhesk** [ixofoundation/ixo-blockchain#130]
how to stake with custom coin denomination since it was gentx successfully on the genesis.json?

**Comment by migueldingli1997** [comment]
Hi @jjhesk. Please look at the scripts in the `scripts/` folder. They are very helpful if you want to understand how to set up a genesis account, especially `run_with_all_data.sh`, which creates some accounts for you.

Running `clean_build.sh` followed by `run_with_all_data.sh` will perform the necessary building, full setup and will start the blockchain up with some dummy accounts!

**Comment by migueldingli1997** [comment]
@jjhesk To answer your question, the `bond_denom` value in your genesis file (genesis.json) is what needs to be changed. The default is 'stake'.
