### ISSUE TITLE
Validating the DID address

### ISSUE THREAD

**Issue by jjhesk** [ixofoundation/ixo-blockchain#131]
I have found that 
`did:dxp:yvjnYLNujCX5qfow3qMCgf/Yl9kobOEqzgwiChyIFGb1GM8AZOeWxsuj7TQk7Aic5EJdzuhevwqW8tDGaMz6yY8YIu5lgbwYihHn`
is still matched with
`^did:(dxp:|sov:)([a-zA-Z0-9]){21,22}([/][a-zA-Z0-9:]+|)$`

is that a bug?

**Comment by migueldingli1997** [comment]
Hi jjhesk. This is accepted as the crucial part of the DID is `([a-zA-Z0-9]){21,22}`. What comes after the slash `/` can be any arbitrary alphanumeric string. Might change this in the future and make it more restrictive. Closing the issue for the meantime. Thanks!
