### ISSUE TITLE
how to generate user address with did doc

### ISSUE THREAD

**Issue by jjhesk** [ixofoundation/ixo-blockchain#146]
I have went through the scripts and found that there is no way to generate a new account user with
`cli add keys myfoousr`
and generate the did doc based on this address. Is that possible to do so?  what is the proper way to obtain the did doc 
```
MIGUEL_DID="did:ixo:4XJLBfGtWSGKSz4BeRxdun"
MIGUEL_DID_FULL="{\"did\":\"did:ixo:4XJLBfGtWSGKSz4BeRxdun\",\"verifyKey\":\"2vMHhssdhrBCRFiq9vj7TxGYDybW4yYdrYh9JG56RaAt\",\"encryptionPublicKey\":\"6GBp8qYgjE3ducksUa9Ar26ganhDFcmYfbZE9ezFx5xS\",\"secret\":{\"seed\":\"38734eeb53b5d69177da1fa9a093f10d218b3e0f81087226be6ce0cdce478180\",\"signKey\":\"4oMozrMR6BXRN93MDk6UYoqBVBLiPn9RnZhR3wQd6tBh\",\"encryptionPrivateKey\":\"4oMozrMR6BXRN93MDk6UYoqBVBLiPn9RnZhR3wQd6tBh\"}}"

```

**Comment by migueldingli1997** [comment]
Hi @jjhesk, ixo blockchain does not use the Cosmos keybase. You can use an existing DID Doc (such as `MIGUEL_DID_FULL`) if you're just trying stuff out. In future versions, we will have ways to generate new DID Docs from the CLI.

**Comment by migueldingli1997** [comment]
To get a Cosmos SDK address from a DID Doc, there's a query that you can use:

`ixocli q did get-address-from-pubkey <verify_key>`
