### ISSUE TITLE
Bonds Module: Improve Doc Around Expected Inputs

### ISSUE THREAD

**Issue by jjhesk** [ixofoundation/ixo-blockchain#152]
To declare the bond type with a token call "ABC" and how does it work with ABC to be having 3 decimal for example 100.123 ABC that can be traded and swapped. How doe it handle on this case?

**Comment by migueldingli1997** [comment]
There are no decimal places involved. 1ABC would be considered the smallest unit of the ABC token. So to have 100.123ABC, one would have to work with 100123ABC (without the decimal point). If a decimal point is strictly required, this has to be added at a higher level as a wrap around the blockchain.

**Comment by jjhesk** [comment]
denom and token name should be declare correctly. 

name: ABC
token: uabc

is that the right way to do so?

**Comment by migueldingli1997** [comment]
The bond name is descriptive and can be anything in reality. The token has to be a valid Cosmos SDK token denomination. Your example `uabc` is 100% valid!

**Comment by jjhesk** [comment]
Please do add some more explanation to the doc for the best practice.. I was getting confused.

**Comment by migueldingli1997** [comment]
Resolved by 2510156
