### ISSUE TITLE
Bonds Module: Prevent Sending To Reserve Addresses

### ISSUE THREAD

**Issue by migueldingli1997** [ixofoundation/ixo-blockchain#162]
A possible solution to this is to have a single reserve module account and then have all bonds internally store the reserve balances, such that the reserve balances of all bonds will add up to the balance of the reserve module account.

**Comment by jjhesk** [comment]
there are bank.keeper and supply.keeper that have the same features

**Comment by migueldingli1997** [comment]
Definitely @jjhesk. We already make use of these modules. It's just a matter of preventing tokens from being sent to reserve addresses because this disrupts calculations.

**Comment by migueldingli1997** [comment]
Closed by #182
