### ISSUE TITLE
bond issuer new features

### ISSUE THREAD

**Issue by jjhesk** [ixofoundation/ixo-blockchain#163]
I wish that there are new features for such items:

1. The website field, `website` optional
2. The whitepaper field for the pdf, 'whitepaper` optional
3. The trading start time upon approvals field, `start_time` required
4. Reports the total holding accounts and the average holding amount from the bond status. `account_sum` and `avg_amount`
5. The voting power by the `delegators` or `validators` from the cosmos-sdk to approve the new issuing bonds where they can receive partial fees from the listing. 
6. using oracle or some sort of module to import the pricing of this bond. `pricing_api`: optional. This feature only approved by `eligiblevoting:1` the biggest delegator enforced.

Is a little complicated for number 5. 
The work flow is like this, bond-creator pays the native token to list the bond and that also creates a proposal for the voters. If the bond-creator is also the biggest delegators or validators then it will automatically approved and to be listed. So there is no approval process needed.

Fields in approval process:
`premium` coin - premium fee. The only coin to be collected is the native token.
`eligiblevoting` - the options for 
1. only delegators
2. only validators
3. delegators or validators only
4. everyone

`vesting` seconds - limited time for voting process countdown
`vest_enforced` bool - force to be able to run thru the entire countdown process

The voting approval = 51% * ( min-fee + premium fee) . The eligible voters are declared on the bond listing config `eligiblevoting`.  
`vest_enforced` = false, any 51% reached will be considered as success

Upon the success of approval process. The fee will be collected and transfer to the staked partners. 

Upon the failure of approval process from the countdown. The 2% of the entire listing fee will be non-refundable. 

That `2%`, `51%` are the fields that declared on the genesis file and that can be changed by proposal government voting.
`approval_percentage: 0.500000`
`nonrefundable_percentage: 0.0200000`

**Comment by ig-shaun** [comment]
Features already in development:

1. Funding entity is associated with the bond. This will become much more obvious with the next big release of the ixo web-client. A Funding entity (like all entities in ixo) has a DID and an associated Entity Document (DDO) record stored on-chain. Includes content links to narrative information, bond metadata and owner/controllers information.
2. Entity document includes information such as the website, social media links, pdf document links - which will meet the bond issuer's need to offer a full prospectus which is compliant with regulations. The interface also enables the bond issuer to manage investors and authorisations, with required credentials such as KYC.
3. The Bond Events feature of will provide information such as actual start time of trading.
4. On the Funding entity UI there is a Dashboard tab on which a report can be provided for the total staked accounts and average staking amounts. Will add this feature request.
5. In the current software release, issuing bonds is permission-less and does not incur listing fees. Besi relayersdes the technical complexity of implementing a governance process around issuing bonds, this could possibly have regulatory implications in some contexts, if the delegators (hub relayers) are implicated in issuing a security offering.
6. The upcoming release of Alpha Bonds will include a deFi protocol-level fee. The specifics of this are still under development, with Blockscience undertaking the crypto-economic engineering design.

There will be a governance feature for voting on proposals, at the level of the Funding Entity. However, this is currently designed for participation by holders of bond tokens.

**Comment by migueldingli1997** [comment]
Closing the issue for now. Thank you for all your questions and suggestions.
