### ISSUE TITLE
Treasury Module: MsgSend ToDid -> ToDidOrAddr

### ISSUE THREAD

**Issue by migueldingli1997** [ixofoundation/ixo-blockchain#167]
The `MsgSend` message in the Treasury module allows an address to be specified as the recipient. However, the `MsgSend` type expects the JSON key to be `to_did` rather than `to_did_or_addr`. This should be fixed.

**Comment by jjhesk** [comment]
this is important to have..

**Comment by migueldingli1997** [comment]
@jjhesk Using an address as the recipient is already possible. What's incorrect is just the naming of the field. This is a small change which will be accomplished by the next version of the ixo blockchain.

**Comment by migueldingli1997** [comment]
Closed by #176
