### ISSUE TITLE
DID: Add Msg and Event for DID Document Changes 

### ISSUE THREAD

**Issue by ig-shaun** [ixofoundation/ixo-blockchain#171]
Explicitly record DID Document Changes as events.
One mitigation against unauthorised changes to a DID document is monitoring and actively notifying the DID subject when there are changes. This is analogous to helping prevent account takeover on conventional username/password accounts by sending password reset notifications to the email addresses on file.

As a verifiable data registry on which the DID is registered, ixo must directly support change notifications.
Relayers who may operate as DID controllers can implement subscription services (e.g. using the ixo-blocksync) to emit notifications that could be sent directly to the relevant service endpoints in the DID document (such as Cell-node) for display through client interfaces.

**Comment by migueldingli1997** [comment]
For this I think we would actually have a DID editing message (`MsgEditDidDoc` for instance) which would be the only way to edit a DID document. This message would emit all the necessary events to indicate what was edited.

**Comment by Michael-Ixo** [comment]
Did module replaced with Iid module since ixo v0.19.0 which has UpdateIidDocument message and events
