### ISSUE TITLE
Review IBC relayers which are compatible with ixo-blockchain

### ISSUE THREAD

**Issue by stefaniatadama** [ixofoundation/ixo-blockchain#244]
After enabling IBC transfers on ixo-blockchain, significant testing was done around using IBC to transfer tokens between ixo and other blockchains. As is, our testing shows that transfers between ixo and other blockchains using a non-forked Cosmos SDK v0.42.4 or higher can be performed using the ts-relayer (see below). For older versions of Cosmos SDK and for blockchains based on a fork of Cosmos SDK, the Hermes relayer can potentially be used, but this hasn't been verified by our own testing yet. This issue is a short report of our testing and the observations we made throughout, as well as a reminder to perform more testing with different relayers in the future.

In the below:
- **gaia** refers to [this](https://github.com/cosmos/gaia) repo at v5.0.4 (commit hash `1b810239668c98efcc717c1d75be176233e57d02`, Cosmos SDK v0.42.9)
- **pandora** refers to [this](https://github.com/ixofoundation/ixo-blockchain) repo at v1.6.0 (commit hash `21e2c962e18220888d529bf156406260a321cf80`, Cosmos SDK v0.42.6)
- **pandora (starport)** refers to pandora as above, but built and started up using [Starport](https://github.com/tendermint/starport)
- **osmosis** refers to the public Osmosis mainnet running osmosis as `osmosis-1`
- **cosmoshub** refers to the public Cosmos mainnet running gaia as `cosmoshub-4`

1) Using [Cosmos relayer](https://github.com/cosmos/relayer):
- gaia <-> gaia worked
- gaia -> pandora worked but pandora -> gaia failed when relaying packets
- pandora (starport) <-> pandora (starport) worked
In all instances, starting the relayer with the command `rly start transfer` crashes after a few seconds. Other people on the ibc-relayer discord channel were having similar issues, and they were advised to try out other relayers.

2) Using [ts-relayer](https://github.com/confio/ts-relayer):
- gaia <-> gaia worked
- pandora <-> gaia worked
- pandora <-> osmosis failed when setting up the relayer. A similar issue [here](https://github.com/confio/ts-relayer/issues/201) indicates that this might be due to osmosis using a fork of Cosmos SDK. This issue states that 'projects that fork the SDK are using the relayer at their own risk'.
- pandora <-> cosmoshub worked - successfully [transferred 1234uixo](https://www.mintscan.io/cosmos/txs/D38D4E17D03673901BE985DE292E2DDDF56008D1C8A5677B55915AD14C6DF3B3) to an address on cosmoshub.

3) [Hermes relayer](https://github.com/informalsystems/ibc-rs) was considered but was not used for testing due to its lack of (simple) documentation for setting it up with networks that are not gaia.

**Comment by Michael-Ixo** [comment]
Extensive testing has been done by ixo and community as a whole where relayers are mostly using the go-relayer or more commonly hermes. Ibc and relayer packages are at a mature enough state where ixo doesnt need to do more as they are community tested and working, as well as tested and working on ixo test net and main net. We also included ibc-go e2e workflow tests in the ixo blockchain repo that tests ibc with every upgrade
