### ISSUE TITLE
more composable/interoperable protos

### ISSUE THREAD

**Issue by pyramation** [ixofoundation/ixo-blockchain#272]
Hello! I'm working on tooling to generate clients, and here to help with packaging protos in a canonical way that other chains are doing

basically right now, ignite cli puts all of the files in the global proto folder. It should instead put them all a folder in the form of `/proto/<chainName>/<moduleName>` to make them more interoperable and composable.

For example, these chains all do it correctly:

- [./proto/stargaze](https://github.com/public-awesome/stargaze/tree/main/proto/stargaze)
- [./proto/osmosis](https://github.com/osmosis-labs/osmosis/tree/main/proto/osmosis)
- [./proto/akash](https://github.com/ovrclk/akash/tree/master/proto/akash)
- [./proto/cosmos](https://github.com/cosmos/cosmos-sdk/tree/main/proto)
- [./proto/juno](https://github.com/CosmosContracts/juno/tree/main/proto)

To make the protos more interoperable, in the example of ixo, we need to now move:

```
proto/bonds            -> proto/ixo/bonds
proto/did      -> proto/ixo/did
proto/payments   -> proto/ixo/payments
proto/project              -> proto/ixo/project
```

if not `ixo`, something that represents your chain name.

And ixo is not the only one, @nghuyenthevinh2000 and others have had to spend a lot of time fixing protos generated from Ignite CLI due to this issue.

**Comment by pyramation** [comment]
A big issue with your protos is that your package will not be very portable. I have made an experimental option that will allow these to work, but I still want to point this out to help improve the interoperability of your project

Here are the upstream issues that have been fixed

https://github.com/ignite/cli/issues/2871 and this comment specifically https://github.com/ignite/cli/issues/2871#issuecomment-1264690290

**Comment by demondayza** [comment]
Thank you for this @pyramation we will get this into our upcoming upgrade!

**Comment by pyramation** [comment]
wow that would be amazing! thanks ;)

**Comment by demondayza** [comment]
Done and Dusted! @pyramation

**Comment by pyramation** [comment]
wow, this is great! :)

**Comment by demondayza** [comment]
Thanks so much for your help and suggestions  @pyramation !
