### ISSUE TITLE
Remove use of time.Now()

### ISSUE THREAD

**Issue by migueldingli1997** [ixofoundation/ixo-blockchain#285]
## Description

The use of `time.Now()` should be completely avoided due to non-determinism. Here's an example of the use of `time.Now()` being reported as a vulnerability in the past: [link](https://forum.cosmos.network/t/cosmos-sdk-vulnerability-retrospective-security-advisory-jackfruit-october-12-2021/5349).

In the scope of testing, this is usually fine to use. However, looking through [here](https://github.com/ixofoundation/ixo-blockchain/search?q=time.Now), it seems like there are instances where it is being used outside of the scope of testing. This should be replaced with `ctx.BlockTime()` which will be the same for all nodes running the blockchain.

**Comment by alwyn-ixo** [comment]
@migueldingli1997 noted

**Comment by Michael-Ixo** [comment]
It has been replaced with ixo v0.20.0 thanks @migueldingli1997
