### ISSUE TITLE
General: Complete Module Specs

### ISSUE THREAD

**Issue by migueldingli1997** [ixofoundation/ixo-blockchain#82]
Each module should have a markdown-based spec written. One can refer to any Cosmos SDK module spec, such as that of the [bank module](https://github.com/cosmos/cosmos-sdk/tree/master/x/bank/spec), as a guideline.

~Since a part of the spec is the listing of events, issue #77 should most likely be completed before.~ (done)

~As a part of the closing of this issue, the Bonds module spec should be updated to reflect the latest changes to (i) messages, (ii) types, (iii) events.~ (done)

As of #177, we now have a draft spec for any module that handles messages or generates events.

**Comment by stefaniatadama** [comment]
Closed due to #246.
