### ISSUE TITLE
General: Validation of Genesis and Messages

### ISSUE THREAD

**Issue by migueldingli1997** [ixofoundation/ixo-blockchain#89]
Validation of the genesis state should be implemented using the already present but blank ValidateGenesis functions in each module. For messages, basic validation can be implemented in the already present but (in some cases) blank or incomplete ValidateBasic functions.

**Comment by migueldingli1997** [comment]
As of #100, message validation has been greatly improved. The remaining verification is not crucial and hence the 'priority' label can be removed.

**Comment by Michael-Ixo** [comment]
From ixo v0.20.0 transactions has ValidateBasic and genesis state for modules also include validation
